//
//  MapInteractor.swift
//  LocalFood
//
//  Created by Eryk Chrustek on 21/11/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates by Patryk Średziński
//

import Foundation

final class MapInteractor: MapDataStore {

    // MARK: Properties
    var presenter: MapPresenting?
    var gateway: APIGateway?
}

// MARK: MapBusinessLogic
extension MapInteractor: MapBusinessLogic {
    func prepareContent(request: Map.Content.Request) {
        let places = [MapPlace(id: "1", category: .shop, name: "Spolem Sp. z o.o", latitude: 50.0639925, longitude: 19.9284556)]
        let response = Map.Content.Response(places: places)
        presenter?.presentContent(response: response)
    }
    
    func prepareDeliveryStatus(request: Map.DuringDelivery.Request) {
        guard let order = Orders.shared.getLastOrder() else { return }
        presenter?.presentDeliveryStatus(response: .init(order: order))
    }
}
